import environment from "./helpers/environment";

module.exports = {
  ROOMS_SOURCE: process.env.ROOMS_SOURCE,
  ENVIRONMENT: process.env.NODE_ENV,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || "XXXX",
  GOOGLE_SECRET: process.env.GOOGLE_SECRET || "XXXX",
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL
    || "http://localhost:8080/auth/google/callback",
  COOKIE_SESSION_SECRET: process.env.COOKIE_SESSION_SECRET || "matrix-session",
  COOKIE_SESSION_MAX_AGE: environment.parseVariable(process.env.COOKIE_SESSION_MAX_AGE)
    || 30 * 24 * 60 * 60 * 1000, // 30 days
  ENFORCE_SSL: process.env.ENFORCE_SSL || "false",
  CUSTOM_STYLE: process.env.CUSTOM_STYLE || "",
  HOST: "0.0.0.0",
  PORT: process.env.PORT || 8080,
  WHITELIST_DOMAINS: environment.parseVariable(process.env.WHITELIST_DOMAINS) || [],
  BIGBLUEBUTTON_URL: process.env.BIGBLUEBUTTON_URL,
  BIGBLUEBUTTON_SECRET: process.env.BIGBLUEBUTTON_SECRET,
  BIGBLUEBUTTON_PASSWORD: process.env.BIGBLUEBUTTON_PASSWORD,
  BIGBLUEBUTTON_WELCOME_MESSAGE: process.env.BIGBLUEBUTTON_WELCOME_MESSAGE,
  BIGBLUEBUTTON_ALWAYS_MODERATOR: process.env.BIGBLUEBUTTON_ALWAYS_MODERATOR,
  BIGBLUEBUTTON_MAX_PARTICIPANTS: process.env.BIGBLUEBUTTON_MAX_PARTICIPANTS,
  BIGBLUEBUTTON_ENABLE_RECORD: process.env.BIGBLUEBUTTON_ENABLE_RECORD,
  BIGBLUEBUTTON_DURATION: process.env.BIGBLUEBUTTON_DURATION,
  BIGBLUEBUTTON_CONTROL_RECORDING: process.env.BIGBLUEBUTTON_CONTROL_RECORDING,
  BIGBLUEBUTTON_WEBCAM_ONLY_MODERATOR: process.env.BIGBLUEBUTTON_WEBCAM_ONLY_MODERATOR,
  BIGBLUEBUTTON_DISABLE_WEBCAM: process.env.BIGBLUEBUTTON_DISABLE_WEBCAM,
  BIGBLUEBUTTON_PRESENTATION: process.env.BIGBLUEBUTTON_PRESENTATION,
  INSTITUTION_NAME: process.env.INSTITUTION_NAME,
  INSTITUTION_SLOGAN: process.env.INSTITUTION_SLOGAN,
  LOGO_URL: process.env.LOGO_URL,
  BACKGROUND_IMAGE_URL: process.env.BACKGROUND_IMAGE_URL,
};
